controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    warthog_joint_publisher:
      type: joint_state_broadcaster/JointStateBroadcaster

    warthog_velocity_controller:
      type: diff_drive_controller/DiffDriveController

warthog_joint_publisher:
  ros__parameters:
    publish_rate: 50.0

warthog_velocity_controller:
  ros__parameters:
    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']

    wheel_separation: 1.5
    wheel_radius: 0.3
    
    wheel_separation_multiplier: 1.125
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    
    open_loop: false
    enable_odom_tf: false

    cmd_vel_timeout: 0.25
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 2

    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 5.0
    linear.x.min_velocity: -5.0
    linear.x.max_acceleration: 50.0
    linear.x.min_acceleration: -50.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.max_acceleration: 40.0
    angular.z.min_acceleration: -40.0

ekf_localization:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    
    odom0: /warthog_velocity_controller/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  true, true, false]
    imu0_differential: false
    
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
